---
title: "Project 1"
author: "Kat Wiles"
date: "Friday, October 24, 2014"
output: html_document
---




###Introduction

When I started on this project, I originally wanted to work with some data from my lab. I struggled with the data processing, which took much more time than expcected. I then got a data set that had already been processed and tried playing around with the package [phyloseq](http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0061217). Phyloseq is an R package that is used to visualize microbiome sample data. I had difficulty using the package with the data that I was given. For example, I was trying to make a relative abundance graph and I could not get the code to work. 

Instead of continuing with this project, I decided to scrap the whole thing and try to see if I could use the sample data on the [phyloseq website](http://joey711.github.io/phyloseq/) and reproduce many of the figures that are in the tutorial. The phyloseq package is designed to help scientists with reproducible data. I thought it would be interesting to see how reproducible their website is. This will also be useful way of learning how to use phyloseq. 

Once I learned how to phyloseq, I played around with the sample data to produce some new figures and graphs. I noted where this was done. #expand upon this. 


###Methods

First 


```{r, echo=FALSE}
library("phyloseq") #load phyloseq library
packageVersion("phyloseq") # getting version number '1.10.0'
data("GlobalPatterns") #loading Global Patterns data set




```

